package com.itcluster.mobile.app.units

import com.itcluster.mobile.app.TileNews
import com.itcluster.mobile.kmm.shared.cache.SharedFactory
import dev.icerock.moko.resources.desc.StringDesc
import dev.icerock.moko.units.TableUnitItem
import javax.inject.Inject

class NewsListUnitsFactory @Inject constructor() : SharedFactory.NewsUnitsFactory {
    override fun createNewsTile(
        id: Long,
        title: String,
        description: StringDesc
    ): TableUnitItem {
        // TileNews is generated by units plugin from https://github.com/icerockdev/moko-units
        // generation based on databinding layouts
        return TileNews().apply {
            itemId = id
            this.title = title
            this.description = description
        }
    }
}
