/**
* GymMind API
* API for GymMind app
*
* OpenAPI spec version: 1.1
* Contact: you@your-company.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.itcluster.mobile.domain.network.api.models

import kotlinx.serialization.Serializable


/**
 * 
 * @param idUser 
 * @param idGame 
 * @param stateGame 
 */
@Serializable
data class GameWordsReq (
    val idUser: String? = null,
    val idGame: String? = null,
    val stateGame: String? = null
)

